package exam8_21.exception;

public class ExceptionTest {
	public static void main(String[] args) {
		method1();
		System.out.println("method()의 수행을 마치고 main메서드로 돌아왔습니다.");
	}
	
	static void method1() {
		try {
			System.out.println("method1()이 호출되었습니다.");
			return;
		} catch(Exception e) {
			e.printStackTrace();
		} finally {
			System.out.println("method1()의 finally블락이 실행되었습니다.");
		}
	}
}
