package exam8.exception;

public class ExceptionTest2 {
	
	public int get50thItem(int[] array) throws Exception {
		return array[49];
	}
	
	public static void main(String[] args) {
		int[] array = new int[10];
		
		try {
			
		} catch(ArrayIndexOutOfBoundsException e) {
			e.printStackTrace();
		}
		
	}
	
}
