package sec1_3.exception3;

public class ExceptionTest1 {
	public static void main(String[] args) {
		int a = 100;
		int b = 0;

		try {
			int result = a / b;
			System.out.println(result);
		} catch (ArithmeticException e) {
			System.out.println("0으로 나눌 수 없습니다.");
		}
	}
}
